CREATE TABLE COMPANY.CARGO(
    CD_CARGO  NUMBER        CONSTRAINT PK_CARGO PRIMARY KEY,
    CARGO     VARCHAR2(150) CONSTRAINT UK_CARGO UNIQUE NOT NULL,
    FLG_ATIVO CHAR(1)       CONSTRAINT CK_CARGO CHECK(FLG_ATIVO IN ('A','I'))
);

COMMENT ON TABLE  COMPANY.CARGO           IS 'Tabela que contém os cargos';
COMMENT ON COLUMN COMPANY.CARGO.FLG_ATIVO IS '[A] ATIVO .:. [I] INATIVO';