CREATE TABLE COMPANY.COLABORADOR(
    CD_MATRICULA NUMBER        CONSTRAINT PK_COLABORADOR            PRIMARY KEY,
    NOME_SOCIAL  VARCHAR2(50)  NOT NULL,
    NOME         VARCHAR2(150) NOT NULL,
    CPF          NUMBER(11)    CONSTRAINT UK_COLABORADOR_CPF        UNIQUE     ,
    DT_NASCIDO   DATE          NOT NULL,
    FL_SEXO      CHAR(1)       CONSTRAINT CK_COLABORADOR_SEXO       CHECK( FL_SEXO IN ('M','F')),
    CD_SETOR     NUMBER        CONSTRAINT FK_SETOR_COLABORADOR      REFERENCES COMPANY.SETOR(CD_SETOR)           NOT NULL,
    CD_GESTOR    NUMBER        CONSTRAINT FK_COLABORADO_COLABORADOR REFERENCES COMPANY.COLABORADOR(CD_MATRICULA) 
);

COMMENT ON TABLE  COMPANY.COLABORADOR           IS 'Principais dados do colaborador vinculado a empresa';
COMMENT ON COLUMN COMPANY.COLABORADOR.FL_SEXO   IS '[F] FEMININO .:. [M] MASCULINO';
COMMENT ON COLUMN COMPANY.COLABORADOR.CD_GESTOR IS 'Código do gestor direto';