CREATE TABLE EMPRESA.SETOR(
    CD_SETOR     NUMBER        CONSTRAINT PK_SETOR       PRIMARY KEY,
    SETOR        VARCHAR2(150) CONSTRAINT UK_PERADOR     UNIQUE     ,
    CD_SUP_SETOR NUMBER        CONSTRAINT FK_SETOR_SETOR REFERENCES EMPRESA.SETOR(CD_SETOR)
);