CREATE TABLE EMPRESA.COLABORADOR(
    CD_MATRICULA NUMBER        CONSTRAINT PK_COLABORADOR            PRIMARY KEY,
    NOME_SOCIAL  VARCHAR2(50)  NOT NULL,
    NOME         VARCHAR2(150) NOT NULL,
    CPF          NUMBER(11)    CONSTRAINT UK_COLABORADOR_CPF        UNIQUE     ,
    DT_NASCIDO   DATE          NOT NULL,
    FL_SEXO      CHAR(1)       CONSTRAINT CK_COLABORADOR_SEXO       CHECK( FL_SEXO IN ('M','F','O')),
    CD_SETOR     NUMBER        CONSTRAINT FK_SETOR_COLABORADOR      REFERENCES EMPRESA.SETOR(CD_SETOR)           NOT NULL,
    CD_GESTOR    NUMBER        CONSTRAINT FK_COLABORADO_COLABORADOR REFERENCES EMPRESA.COLABORADOR(CD_MATRICULA) ,
    DT_REGISTRO  DATE          NOT NULL,
    OPERADOR     VARCHAR2(30)  NOT NULL
);