CREATE FUNCTION COMPANY.GERAR_MATRICULA RETURN NUMBER
IS
    CODE NUMBER;
BEGIN
    SELECT
        TO_CHAR(SYSDATE,'YYYYMM')||LPAD(COUNT(1),5,'0')||'000'
        INTO
        CODE
    FROM
        COMPANY.COLABORADOR_AUD A
    WHERE
        TRUNC(A.DT_AUDITORIA,'MM') = TRUNC(SYSDATE,'MM')
    AND A.FL_ACAO = 'I';
    
    RETURN CODE;
END;
