INSERT INTO COMPANY.SETOR
(CD_SETOR,SETOR,CD_SUP_SETOR)
VALUES (1,'INFORMÁTICA',NULL);
    
INSERT INTO COMPANY.SETOR
(CD_SETOR,SETOR,CD_SUP_SETOR)
VALUES (COMPANY.SQ_SETOR.NEXTVAL,'DESENVOLVIMENTO',1);

INSERT INTO COMPANY.SETOR
(CD_SETOR,SETOR,CD_SUP_SETOR)
VALUES (2,'ADMINISTRAÇÃO',NULL);

INSERT INTO COMPANY.SETOR
(CD_SETOR,SETOR,CD_SUP_SETOR)
VALUES (COMPANY.SQ_SETOR.NEXTVAL,'PORTARIA',2);

INSERT INTO COMPANY.SETOR
(CD_SETOR,SETOR,CD_SUP_SETOR)
VALUES (COMPANY.SQ_SETOR.NEXTVAL,'SERVIÇOS GERAIS',2);

INSERT INTO COMPANY.SETOR
(CD_SETOR,SETOR,CD_SUP_SETOR)
VALUES (3,'FINANCEIRO',NULL);
    
INSERT INTO COMPANY.SETOR
(CD_SETOR,SETOR,CD_SUP_SETOR)
VALUES (COMPANY.SQ_SETOR.NEXTVAL,'RECEPÇÃO',2);

INSERT INTO COMPANY.SETOR
(CD_SETOR,SETOR,CD_SUP_SETOR)
VALUES (COMPANY.SQ_SETOR.NEXTVAL,'FATURAMENTO',3);

COMMIT;
