CREATE TABLE COMPANY.COLABORADOR_AUD(
    CD_AUDITORIA NUMBER        CONSTRAINT PK_COLABORADOR_AUD PRIMARY KEY,
    CD_MATRICULA NUMBER        ,
    NOME_SOCIAL  VARCHAR2(50)  ,
    NOME         VARCHAR2(150) ,
    CPF          NUMBER(11)    ,
    DT_NASCIDO   DATE          ,
    FL_SEXO      CHAR(1)       ,
    CD_SETOR     NUMBER        ,
    CD_GESTOR    NUMBER        ,
    FL_ACAO      CHAR(1)       CONSTRAINT CK_COLABORADOR_AUD CHECK(FL_ACAO IN ('I','U','D')),
    DT_AUDITORIA DATE          NOT NULL,
    LG_OPERADOR  VARCHAR(30)   NOT NULL
);

COMMENT ON TABLE  COMPANY.COLABORADOR_AUD          IS 'Auditoria tabela colaborador';
COMMENT ON COLUMN COMPANY.COLABORADOR_AUD.FL_ACAO  IS '[I] INSERT .:. [U] UPDATING .:. [D] DELETING';
