CREATE TABLE COMPANY.SETOR_AUD(
    CD_AUDITORIA NUMBER        CONSTRAINT PK_SETOR_AUD       PRIMARY KEY,
    CD_SETOR     NUMBER        ,
    SETOR        VARCHAR2(150) ,
    CD_SUP_SETOR NUMBER        ,
    FL_ACAO      CHAR(1)       CONSTRAINT CK_SETOR_AUDITORIA CHECK(FL_ACAO IN ('I','U','D')),
    DT_AUDITORIA DATE          NOT NULL,
    LG_AUDITORIA VARCHAR2(30)  NOT NULL
);

COMMENT ON TABLE  COMPANY.SETOR_AUD              IS 'Tabela contendo os setores de uma empresa';
COMMENT ON COLUMN COMPANY.SETOR_AUD.CD_SUP_SETOR IS '[I] INSERT .:. [U] UPDATE .:. [D] DELETE';